### ISSUE TITLE
README example matching `route.url`

### ISSUE THREAD

**Issue by Frikki** [TylorS/cycle-director#1]
In your example on the README, you test the `route.url` against `currentRoute` with strong equality. This requires the URL to match exactly the current route. However, in many cases, you’d want to match a route URL such as `/users/:user` or a _not found_ wildcard `*`. Director can do that, so why are you not using this functionality in the example? Wouldn’t it make sense to take the client-side routing example from the [Director README](https://github.com/flatiron/director#client-side-routing) and show that with cycle-director?

**Comment by TylorS** [comment]
That's a good point, I honestly just threw something together really quickly. I'll work on updating the example to more closely match the director examples when I get home from work. Thank you for the suggestion.

**Comment by TylorS** [comment]
I don't believe in the current state of this driver routes like `/users/:user` would work in any straight forward way. Currently Router returns `/ + router.getRoute()` which works perfectly fine with routes that I have in my example. With a route like `/users/:userId`, lets say you navigate to `/users/1` you would be returned `/users,1`. This is because `router.getRoute()` returns an array of the parts that make up the url and I'm concatenating it with a string. 

That's my bad for only using my example code to 'test' it. I'm certainly going to look into a way to fix that problem as well as update the README.

Going to open another issue to reference this problem.

**Comment by TylorS** [comment]
The README has been updated to more closely match that of director's README. It has also been updated to match some changes I've made.
